export const photoMap = {
 'hikvision-colorvu': ['hikvision-colorvu', 'Hikvision ColorVu camera'],
 'hikvision-outdoor': ['hikvision-outdoor', 'Hikvision outdoor camera'],
 'hikvision-hybrid': ['hikvision-hybrid', 'Hikvision hybrid light camera'],
 'hikvision-dome': ['hikvision-outdoor', 'Representative Hikvision dome camera'],
 doorbell: ['tapo-chime', 'TP-Link Tapo H100 smart hub with chime'],
 intercom: ['ezviz-intercom', 'EZVIZ HP7 video intercom with indoor monitor and outdoor door station'],
 'video-doorbell': ['eufy-e340', 'eufy Security Video Doorbell E340 with chime and dual cameras'],
 solar: ['imou-solar', 'Imou Cell PT 3MP outdoor security camera with 3W solar panel'],
 wifi: ['access-point', 'TP-Link EAP225 ceiling-mount wireless access point'],
 router: ['ruijie-router-white', 'White Ruijie Reyee wireless gateway router'],
 'router-black': ['ruijie-router-black', 'Black Ruijie Reyee wireless gateway router'],
 mesh: ['mesh-system', 'TP-Link Deco X20 mesh Wi-Fi system'],
 ezviz: ['ezviz-c6n-3k', 'EZVIZ C6N G1-3K indoor camera with call button and mobile viewing'],
 poe: ['poe-switch', 'Network equipment with connected cables'],
 fiber: ['fiber-links', 'Telecommunications cable connections'],
 'service-wifi': ['service-wifi', 'Network infrastructure in a server enclosure'],
 'service-camera': ['service-security', 'Smart security cameras and sensors'],
 'service-router': ['service-smart', 'Using a smart home control panel'],
 'service-switch': ['service-cabling', 'Structured cabling connected to network equipment'],
 camera: ['eufy-outdoor', 'eufy outdoor security camera'],
 indoor: ['indoor-camera', 'Compact white indoor security camera'],
 switch: ['network-switch', 'Ethernet connections on a network switch'],
 cable: ['ethernet-cabling', 'Ethernet patch cables connected to network equipment'],
 rack: ['network-rack', 'Network equipment and structured cable connections'],
 smart: ['lighting', 'Smart light bulbs and mobile controls'],
 control: ['control-panel', 'Wall-mounted smart light switch'],
 office: ['office', 'Bright contemporary office workspace']
};
export const products = [
 {id:19,type:'hikvision-colorvu',category:'CCTV & security',brand:'Hikvision',name:'Hikvision ColorVu Camera',desc:'Plan clear security coverage with a ColorVu camera.',badge:'ColorVu Camera',details:['Hikvision ColorVu camera range','Camera placement and recording setup','Exact model and specifications confirmed with your quote']},
 {id:20,type:'hikvision-outdoor',category:'Outdoor cameras',brand:'Hikvision',name:'Hikvision Outdoor Camera',desc:'Monitor entrances and outdoor areas around your property.',badge:'Outdoor Camera',details:['Outdoor security camera selection','Coverage and mounting assessment','Exact model and weather rating confirmed with your quote']},
 {id:21,type:'hikvision-hybrid',category:'CCTV & security',brand:'Hikvision',name:'Hikvision Hybrid Light Camera',desc:'Explore hybrid light camera options for your security setup.',badge:'Hybrid Light Camera',details:['Hikvision hybrid light camera range','Lighting and recording configuration','Exact model and specifications confirmed with your quote']},
 {id:22,type:'hikvision-dome',category:'CCTV & security',brand:'Hikvision',name:'Hikvision Dome Camera',desc:'Dome-style surveillance for your home or business.',badge:'Dome Camera',details:['Hikvision dome camera selection','Mounting and coverage planning','Representative image; exact model confirmed with your quote']},
 {id:1,type:'wifi',category:'Wi-Fi & networking',brand:'WIRELESS COVERAGE',name:'Wireless access points',desc:'Extend coverage across rooms and workspaces.',badge:'Wi-Fi',details:['Indoor coverage planning','Ceiling or wall mounting options','Configuration for your existing network']},
 {id:13,type:'camera',category:'Outdoor cameras',brand:'OUTDOOR SECURITY',name:'Outdoor CCTV cameras',desc:'Protect entrances, driveways, and perimeter areas.',badge:'Outdoor cameras',details:['Choose a model rated for the installation environment','Plan camera coverage and recording','Mobile viewing configuration for compatible systems']},
 {id:2,type:'ezviz',category:'CCTV & security',brand:'EZVIZ',name:'EZVIZ C6N G1-3K Camera',summary:'3K indoor monitoring with smart tracking and a call button.',desc:'5MP indoor Wi-Fi camera for home and baby monitoring, with a call button, human detection, color night vision, and auto-zoom tracking.',badge:'Indoor camera',details:['Call button for easy communication','Indoor Wi-Fi surveillance and baby monitoring','5MP / 3K imaging','2.4GHz Wi-Fi connectivity','Human detection','Color night vision','Auto-zoom tracking','Supports storage up to 512GB']},
 {id:3,type:'router',category:'Wi-Fi & networking',brand:'RUIJIE REYEE',name:'Wireless gateway router — White',desc:'Bring your internet connection and devices together.',badge:'White router',details:['White Ruijie Reyee router','Check compatibility with your connection','Wi-Fi and network configuration','Device connectivity and handover support']},
 {id:18,type:'router-black',category:'Wi-Fi & networking',brand:'RUIJIE REYEE',name:'Wireless gateway router — Black',desc:'Connect your home or workspace with a wireless gateway.',badge:'Black router',details:['Black Ruijie Reyee router','Check compatibility with your connection','Wi-Fi and network configuration','Device connectivity and handover support']},
 {id:4,type:'switch',category:'Cabling & accessories',brand:'NETWORK ESSENTIALS',name:'Gigabit network switches',desc:'Connect computers, access points, and other equipment.',badge:'Wired networking',details:['Port count matched to your setup','Managed and unmanaged options','Rack or desktop installation planning']},
 {id:5,type:'mesh',category:'Wi-Fi & networking',brand:'WHOLE-HOME CONNECTIVITY',name:'Mesh Wi-Fi systems',desc:'Coordinated wireless coverage for multi-room spaces.',badge:'Home Wi-Fi',details:['Node placement based on your property','Wired backhaul options where suitable','Wi-Fi setup and device reconnection']},
 {id:6,type:'indoor',category:'CCTV & security',brand:'INDOOR MONITORING',name:'Indoor Wi-Fi cameras',desc:'A convenient view of indoor areas from your phone.',badge:'Indoor security',details:['Placement and connectivity advice','Mobile app and account setup guidance','Storage and recording options to discuss']},
 {id:7,type:'poe',category:'Cabling & accessories',brand:'POWER & CONNECTIVITY',name:'PoE network switches',desc:'Network connectivity and compatible device power.',badge:'PoE',details:['Match PoE standards to your devices','Calculate the required power budget','Plan ports for cameras and access points']},
 {id:8,type:'cable',category:'Cabling & accessories',brand:'STRUCTURED CABLING',name:'CAT6 cabling & patch leads',desc:'Organized wired connections from rack to workspace.',badge:'CAT6',details:['Cable-route and length planning','Termination and connection checks','Labelling and tidy cable management']},
 {id:9,type:'rack',category:'Cabling & accessories',brand:'RACK ORGANIZATION',name:'Network racks & patch panels',desc:'Keep network equipment accessible and organized.',badge:'Infrastructure',details:['Rack sizing and equipment layout','Patch-panel and cable-manager selection','Labelling for easier future maintenance']},
 {id:10,type:'fiber',category:'Cabling & accessories',brand:'FIBER CONNECTIONS',name:'Fiber optic connectivity',desc:'Plan the right fiber links for your network.',badge:'Fiber optics',details:['Link distance and connector assessment','Compatible fiber accessories','Installation scope confirmed after assessment']},
 {id:11,type:'smart',category:'Smart home',brand:'CONNECTED LIVING',name:'Smart lighting & accessories',desc:'Explore connected lighting and everyday controls.',badge:'Smart home',details:['Check existing device compatibility','App and network setup','Scenes and everyday control guidance']},
 {id:12,type:'control',category:'Smart home',brand:'HOME AUTOMATION',name:'Smart home controls',desc:'Bring compatible connected devices into one routine.',badge:'Automation',details:['Compatibility review before selection','Control and connectivity planning','Setup walkthrough for your household']},
 {id:14,type:'doorbell',category:'Smart devices',brand:'ENTRY SOLUTIONS',name:'Doorbells & chimes',desc:'A clear welcome at your front door, with a setup that fits your home.',badge:'Doorbells',details:['Wired and wireless options to discuss','Check power and chime compatibility','Mounting and setup guidance']},
 {id:15,type:'intercom',category:'Smart devices',brand:'DOOR COMMUNICATION',name:'Video intercom systems',desc:'See and speak with visitors from a compatible indoor station.',badge:'Intercom',details:['Indoor monitor and entrance station planning','Audio and video options matched to your property','Door-release integration subject to compatibility']},
 {id:16,type:'video-doorbell',category:'Smart devices',brand:'EUFY SECURITY',name:'eufy Video Doorbell E340 with Chime',summary:'Dual-camera doorbell with 2K video and a wireless chime.',desc:'Battery-powered Wi-Fi video doorbell with dual cameras, Delivery Guard, 2K Full HD, and color night vision.',badge:'Wi-Fi doorbell cameras',details:['Battery-powered E340 with chime','Dual cameras with Delivery Guard','2K Full HD video','Color night vision','HomeBase S380 compatible','No monthly fee']},
 {id:17,type:'solar',category:'Outdoor cameras',brand:'IMOU',name:'Imou Cell PT 3MP Solar Camera',summary:'3MP outdoor monitoring with a dedicated 3W solar panel.',desc:'Wireless outdoor surveillance camera for home security, supplied with a new 3W solar panel.',badge:'Solar cameras',details:['Cell PT 3MP security camera for home','Wireless outdoor surveillance','Dome surveillance camera','Solar-powered setup with new 3W solar panel']}
];
export const faqs = [
 ['Can you help me choose equipment?', 'Yes. Share your property type, the rooms or areas you want to cover, your existing equipment, and the problem you want to solve. SKY TECH can discuss suitable options before preparing a quote.'],
 ['Can I upgrade my existing Wi-Fi network?', 'An upgrade can often build on your current equipment. The team will need to check your router, connection, cable layout, and coverage requirements before recommending extra access points or a replacement setup.'],
 ['What is included in an installation quote?', 'Ask for an itemized scope covering equipment, cabling, mounting, configuration, and handover. The final scope and price depend on the property, equipment selected, and work required.'],
 ['Can I view my security cameras on my phone?', 'Many compatible camera systems support mobile viewing. Available features depend on the model, recording setup, app, and internet connection. Remote access should be configured with appropriate account security.'],
 ['Do you help with offices and shops?', 'SKY TECH provides network setup, cabling, camera installation, and IT support for homes and businesses. Share the number of users, connected devices, and your layout to discuss a suitable setup.'],
 ['How do I confirm availability and pricing?', 'Add equipment to the quote basket and send the prepared request through WhatsApp. The team will confirm exact models, availability, installation requirements, and current pricing before you place an order.']
];
