import { createIcons, MapPin, Phone, ShoppingBag, MessageCircle, Menu, ArrowUpRight, ArrowRight, BadgeCheck, Wifi, ShieldCheck, Wrench, Headset, Cctv, House, Network, Check, Search, Plus, ScanLine, Cable, ArrowUp, X, Trash2 } from 'lucide';
import './style.css';
import './readability.css';
import './brand-contact.css';
import './brand-showcase.css';
import './hero.css';
import './layout-polish.css';
import './navigation.css';
import { setupNavigation } from './navigation.js';
import { mountHero } from './hero.js';
import { products, photoMap, faqs } from './catalogue.js';
const icons = { MapPin, Phone, ShoppingBag, MessageCircle, Menu, ArrowUpRight, ArrowRight, BadgeCheck, Wifi, ShieldCheck, Wrench, Headset, Cctv, House, Network, Check, Search, Plus, ScanLine, Cable, ArrowUp, X, Trash2 };

const whatsappIcon = () => '<img class="whatsapp-logo" src="/assets/whatsapp.svg" alt="" width="23" height="23" aria-hidden="true"/>';
const icon = (name, cls = '') => name === 'message-circle' ? whatsappIcon() : `<i data-lucide="${name}" class="${cls}"></i>`;
const wa = 'https://wa.me/971569175353';
const productArt = (type) => { const [file, alt] = photoMap[type] || photoMap.rack; return `<img class="equipment-photo" src="/assets/${file}.jpg" alt="${alt}" loading="lazy" decoding="async" width="1000" height="667"/>`; };
const services = [
 {id:'wifi',icon:'wifi',title:'Wi-Fi & networking',copy:'Better coverage. Fewer interruptions. Stay connected in every corner.',features:['Wi-Fi & mesh installation','Router & access point setup','Network configuration'],tag:'A stronger connection'},
 {id:'camera',icon:'cctv',title:'CCTV & security',copy:'Keep an eye on what matters, wherever your day takes you.',features:['Indoor & outdoor cameras','NVR setup & remote viewing','Maintenance & support'],tag:'Peace of mind, installed'},
 {id:'router',icon:'house',title:'Smart home solutions',copy:'Make everyday living simpler with a home that works together.',features:['Smart device installation','Connected home setup','App configuration'],tag:'A more connected home'},
 {id:'switch',icon:'network',title:'Cabling & IT support',copy:'A reliable foundation, from the first cable to the final connection.',features:['CAT6 & fiber optic cabling','Rack dressing & organization','Troubleshooting & IT support'],tag:'Built right. From the start.'}
];
let basket; try {basket = JSON.parse(localStorage.getItem('sky-basket') || '[]').filter(x => products.some(p => p.id === x.id) && Number.isInteger(x.qty) && x.qty > 0)} catch {basket=[]}
document.querySelector('#app').innerHTML = `
 <div class="topbar"><div class="container top-inner"><span>${icon('map-pin')} Your local technology partner in Abu Dhabi</span><a href="tel:+971569175353">${icon('phone')} +971 56 917 5353 <span class="top-hours">Let’s get you connected</span></a></div></div>
 <header><div class="container header-inner"><a class="brand" href="#" aria-label="SKY TECH home"><span class="brand-mark"><img src="/assets/logo.jpg" alt=""/></span><span><strong><em>SKY</em> TECH</strong><small>Information Technology & Network Services</small></span></a><nav aria-label="Main navigation"><a class="active" href="#">Home</a><a href="#services">Our services</a><a href="#shop">Shop products</a><a href="#about">About us</a><a href="#contact">Contact</a></nav><div class="header-actions"><button class="basket-trigger icon-button" aria-label="Open quote basket">${icon('shopping-bag')}<span class="basket-count" hidden>0</span></button><button class="menu-toggle icon-button" aria-label="Open navigation" aria-expanded="false">${icon('menu')}</button></div></div></header>
 <main><section class="hero"><img class="hero-image" src="/assets/abu-dhabi.jpg" alt="Etihad Towers on the Abu Dhabi skyline"/><div class="hero-shade"></div><div class="container hero-content"><div class="eyebrow light"><span></span> CONNECTING HOMES. EMPOWERING BUSINESSES.</div><h1>Better connected.<br>Better protected.<br><span>Right here in Abu Dhabi.</span></h1><p>Reliable Wi-Fi, smarter security, and technology that just works.<br class="desktop-break"> Expert equipment and installation, all in one place.</p><div class="hero-buttons"><button class="button primary" data-book>Book a site consultation ${icon('arrow-up-right')}</button><a class="button glass" href="#shop">Explore products ${icon('arrow-right')}</a></div><div class="hero-note">${icon('badge-check')} Local expertise <span>•</span> Professional installation <span>•</span> Ongoing support</div></div><div class="hero-caption"><span class="location-dot"></span> ABU DHABI, UAE <small>Our city. Your connection.</small></div></section>
 <div class="benefits"><div class="container benefits-inner">${[['wifi','Wi-Fi without limits','Coverage where you need it'],['shield-check','Security made simple','Keep what matters protected'],['wrench','Installed by experts','Care in every connection'],['headset','Support that stays','A local team you can reach']].map(([i,t,s])=>`<div>${icon(i)}<span><strong>${t}</strong><small>${s}</small></span></div>`).join('')}</div></div>
 <section id="services" class="section container"><div class="section-heading"><div><div class="eyebrow">WHAT WE DO</div><h2>One team. Every connection.</h2><p>From a single access point to a complete business network, we’ve got you covered.</p></div><a href="#contact" class="text-link">Find your solution ${icon('arrow-up-right')}</a></div><div class="service-grid">${services.map(s=>`<article class="service-card"><div class="service-art art-${s.id}">${productArt(s.id === 'router' ? 'smart' : s.id)}<span class="art-label">${s.tag}</span></div><div class="service-body"><span class="service-icon">${icon(s.icon)}</span><h3>${s.title}</h3><p>${s.copy}</p><ul>${s.features.map(f=>`<li>${icon('check')}${f}</li>`).join('')}</ul><button class="text-link" data-service="${s.id}">Explore service ${icon('arrow-right')}</button></div></article>`).join('')}</div></section>
 <section id="brands" class="brand-strip" aria-labelledby="brands-heading"><div class="container brand-strip-inner"><div class="brand-intro"><div class="eyebrow">QUALITY YOU RECOGNIZE</div><h2 id="brands-heading">Great connections. <br>Recognized names.</h2><p>Equipment from the brands you know, <br>selected for the space you need.</p></div><div class="brand-showcase"><div class="brand-logo-row"><a href="https://www.tp-link.com/" target="_blank" rel="noopener" class="brand-logo brand-tplink" aria-label="Visit TP-Link official website"><img src="/assets/brands/tp-link.jpg" alt="TP-Link" width="500" height="333" loading="lazy"/></a><a href="https://www.ruijie.com/en-global/" target="_blank" rel="noopener" class="brand-logo brand-ruijie" aria-label="Visit Ruijie official website"><img src="/assets/brands/ruijie.svg" alt="Ruijie Networks" loading="lazy"/></a><a href="https://www.ip-com.com.cn/en/" target="_blank" rel="noopener" class="brand-logo brand-ipcom" aria-label="Visit IP-COM official website"><img src="/assets/brands/ip-com.jpg" alt="IP-COM — World Wide Wireless" width="738" height="210" loading="lazy"/></a></div><div class="brand-capabilities"><span>WIRELESS & NETWORKING</span><span>CAT6 CABLING</span><span>FIBER CONNECTIVITY</span></div></div></div></section>
 <section id="shop" class="section container"><div class="section-heading"><div><div class="eyebrow">THE RIGHT TECH FOR YOUR SPACE</div><h2>Upgrade your everyday.</h2><p>Explore our equipment range. We’ll help you find the right fit.</p></div><button class="text-link" data-book>Need help choosing? ${icon('arrow-up-right')}</button></div><div class="shop-toolbar"><div class="filters" role="group" aria-label="Product category">${['All products','Wi-Fi & networking','CCTV & security','Cabling & accessories','Smart home'].map((t,i)=>`<button class="filter ${i===0?'selected':''}" data-filter="${t}">${t}</button>`).join('')}</div><label class="search">${icon('search')}<input id="product-search" type="search" placeholder="Find a product…" aria-label="Search products"/></label></div><div class="product-grid" id="products"></div><p class="catalogue-note">Explore equipment categories, with representative stock photography. Exact models, specifications, availability, and pricing are confirmed with your quote.</p></section>

 <section class="solutions-section"><div class="container section"><div class="section-heading"><div><div class="eyebrow">SOLUTIONS FOR YOUR SPACE</div><h2>Different spaces. The same attention to detail.</h2><p>Choose a starting point. We’ll shape the setup around the way you live and work.</p></div></div><div class="solutions-grid">
 <article class="solution-card"><img class="equipment-photo" src="/assets/smart-home.jpg" alt="Connected home devices, tablet and smart lighting" loading="lazy" decoding="async" width="1000" height="667"/><div><span class="eyebrow">FOR YOUR HOME</span><h3>A home that stays connected.</h3><p>From family video calls to connected lighting, give your everyday devices a network that works together.</p><ul><li><i data-lucide="check"></i> Room-by-room Wi-Fi planning</li><li><i data-lucide="check"></i> Smart device setup</li><li><i data-lucide="check"></i> Indoor and entrance monitoring</li></ul><button class="text-link" data-book>Plan my setup <i data-lucide="arrow-up-right"></i></button></div></article><article class="solution-card"><img class="equipment-photo" src="/assets/office.jpg" alt="Bright contemporary office workspace" loading="lazy" decoding="async" width="1000" height="667"/><div><span class="eyebrow">FOR YOUR BUSINESS</span><h3>Keep your workplace moving.</h3><p>Build a practical foundation for desks, meeting rooms, cameras, and the devices your team relies on.</p><ul><li><i data-lucide="check"></i> Office Wi-Fi and wired networks</li><li><i data-lucide="check"></i> Switches, racks, and structured cabling</li><li><i data-lucide="check"></i> Configuration and troubleshooting</li></ul><button class="text-link" data-book>Plan my setup <i data-lucide="arrow-up-right"></i></button></div></article><article class="solution-card"><img class="equipment-photo" src="/assets/outdoor-camera.jpg" alt="Wall-mounted outdoor security camera" loading="lazy" decoding="async" width="1000" height="667"/><div><span class="eyebrow">FOR YOUR PEACE OF MIND</span><h3>See more of what matters.</h3><p>Discuss a camera layout around your entrances and shared areas, with recording and viewing options that suit your needs.</p><ul><li><i data-lucide="check"></i> Camera positioning advice</li><li><i data-lucide="check"></i> Recorder and storage planning</li><li><i data-lucide="check"></i> Mobile viewing setup</li></ul><button class="text-link" data-book>Plan my setup <i data-lucide="arrow-up-right"></i></button></div></article>
 </div></div></section>
 <section class="section container installation-section"><div class="installation-photo"><img class="equipment-photo" src="/assets/network-rack.jpg" alt="Network equipment and structured cable connections" loading="lazy" decoding="async" width="1000" height="667"/><span>Every connection deserves attention.</span></div><div class="installation-copy"><div class="eyebrow">MORE THAN EQUIPMENT</div><h2>The details make<br>the difference.</h2><p>A well-planned installation is easier to use, manage, and maintain. We help connect the pieces, from cable routing to the final device setup.</p><div class="installation-points"><div><span>01</span><div><h3>Plan the connections</h3><p>Discuss coverage, device locations, cable routes, and the equipment already in place.</p></div></div><div><span>02</span><div><h3>Keep the setup organized</h3><p>Consider clear labelling, accessible equipment, and tidy cable management.</p></div></div><div><span>03</span><div><h3>Make the handover useful</h3><p>Walk through the setup, everyday controls, and the next steps for support.</p></div></div></div><button class="text-link" data-book>Discuss your installation <i data-lucide="arrow-right"></i></button></div></section>
  <section id="about" class="about"><div class="container about-inner"><div class="about-copy"><div class="eyebrow light">GOOD TECHNOLOGY. GREAT PEOPLE.</div><h2>Your local experts.<br>From setup to support.</h2><p>Technology should make your life easier. At SKY TECH, we bring your network, security, and connected devices together—with thoughtful installation and a team you can actually talk to.</p><a href="#contact" class="button white">Let’s talk about your space ${icon('arrow-up-right')}</a></div><div class="about-grid">${[['scan-line','Designed around you','Practical solutions for your home, villa, office, or business.'],['cable','Neat. Organized. Reliable.','Careful cabling and tidy installations that are easy to maintain.'],['map-pin','Based in Abu Dhabi','A local team with a hands-on approach to your technology.'],['headset','Here when you need us','Configuration, troubleshooting, and support after setup.']].map(([i,t,p])=>`<div>${icon(i)}<h3>${t}</h3><p>${p}</p></div>`).join('')}</div></div></section>
 <section class="section container process"><div><div class="eyebrow">STRAIGHTFORWARD FROM DAY ONE</div><h2>A better setup starts<br>with a conversation.</h2><p>Tell us what you need. We’ll take it from there.</p></div><div class="steps">${[['01','Tell us about your space','Share your requirements and the issues you want to solve.'],['02','Get a tailored recommendation','We’ll help plan the right equipment and installation.'],['03','Get connected','Our team installs, configures, and walks you through your setup.']].map(([n,t,p])=>`<div><span>${n}</span><h3>${t}</h3><p>${p}</p></div>`).join('')}</div></section>

 <section class="section container faq-section"><div><div class="eyebrow">A LITTLE CLARITY BEFORE YOU START</div><h2>Good questions.<br>Clear answers.</h2><p>Not sure where to begin? A conversation with our team is a good first step.</p><a class="text-link" href="https://wa.me/971569175353" target="_blank" rel="noopener">Ask us on WhatsApp <i data-lucide="arrow-up-right"></i></a></div><div class="faq-list"><details><summary>Can you help me choose equipment?<i data-lucide="plus"></i></summary><p>Yes. Share your property type, the rooms or areas you want to cover, your existing equipment, and the problem you want to solve. SKY TECH can discuss suitable options before preparing a quote.</p></details><details><summary>Can I upgrade my existing Wi-Fi network?<i data-lucide="plus"></i></summary><p>An upgrade can often build on your current equipment. The team will need to check your router, connection, cable layout, and coverage requirements before recommending extra access points or a replacement setup.</p></details><details><summary>What is included in an installation quote?<i data-lucide="plus"></i></summary><p>Ask for an itemized scope covering equipment, cabling, mounting, configuration, and handover. The final scope and price depend on the property, equipment selected, and work required.</p></details><details><summary>Can I view my security cameras on my phone?<i data-lucide="plus"></i></summary><p>Many compatible camera systems support mobile viewing. Available features depend on the model, recording setup, app, and internet connection. Remote access should be configured with appropriate account security.</p></details><details><summary>Do you help with offices and shops?<i data-lucide="plus"></i></summary><p>SKY TECH provides network setup, cabling, camera installation, and IT support for homes and businesses. Share the number of users, connected devices, and your layout to discuss a suitable setup.</p></details><details><summary>How do I confirm availability and pricing?<i data-lucide="plus"></i></summary><p>Add equipment to the quote basket and send the prepared request through WhatsApp. The team will confirm exact models, availability, installation requirements, and current pricing before you place an order.</p></details></div></section>
  <section id="contact" class="contact-section container"><div><div class="eyebrow">LET’S GET STARTED</div><h2>Your next connection starts here.</h2><p>Planning an upgrade or need a little expert advice? We’re a message away.</p></div><div><a class="button whatsapp" href="${wa}" target="_blank" rel="noopener">${icon('message-circle')} Chat on WhatsApp ${icon('arrow-up-right')}</a><a class="contact-phone" href="tel:+971569175353">or call +971 56 917 5353</a></div></section>
 </main><footer class="site-footer"><div class="container footer-banner"><div><span class="eyebrow">YOUR LOCAL TECHNOLOGY PARTNER</span><h2>Good connections start with us.</h2></div><a href="tel:+971569175353" class="footer-call">${icon('phone')}<span>Let’s talk about your next setup<strong>+971 56 917 5353</strong></span>${icon('arrow-up-right')}</a></div><div class="container footer-main"><div class="footer-identity"><a class="footer-brand" href="#"><span class="footer-wordmark">SKY <b>TECH</b></span><span>Information Technology<br>& Network Services</span></a><p>Thoughtful technology for your home and business. From the first connection to everyday support, right here in Abu Dhabi.</p><span class="footer-location">${icon('map-pin')} Abu Dhabi, United Arab Emirates</span></div><div class="footer-links"><strong>Explore</strong><a href="#services">Our services</a><a href="#shop">Shop equipment</a><a href="#brands">Our brands</a><a href="#about">About SKY TECH</a><a href="#contact">Contact us</a></div><div class="footer-links"><strong>What we do</strong><a href="#services">Wi-Fi & networking</a><a href="#services">CCTV & security</a><a href="#services">Smart home setup</a><a href="#services">Cabling & IT support</a><button class="footer-consult" data-book>Request a consultation ${icon('arrow-up-right')}</button></div><div class="footer-contact"><strong>Get in touch</strong><a href="tel:+971569175353">+971 56 917 5353</a><a href="tel:+971585332688">+971 58 533 2688</a><a class="footer-email" href="mailto:skytech.technologyservice@gmail.com">skytech.technologyservice@gmail.com</a><p>East Baniyas 8 Street<br>Baniyas District, Abu Dhabi, UAE</p><a href="https://www.google.com/maps/search/?api=1&query=East+Baniyas+8+Street+Abu+Dhabi" target="_blank" rel="noopener">View area on map ${icon('arrow-up-right')}</a></div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} SKY TECH. All rights reserved.</span><span>Connected. Protected. Supported. · <a href="/image-credits.html" target="_blank" rel="noopener">Photo credits</a></span><a href="#" aria-label="Back to top">${icon('arrow-up')}</a></div></footer>
 <a class="floating-call" href="tel:+971569175353" aria-label="Call SKY TECH on +971 56 917 5353" title="Call SKY TECH">${icon('phone')}</a><a class="floating-whatsapp" href="${wa}" target="_blank" rel="noopener" aria-label="Chat with SKY TECH on WhatsApp" title="Chat on WhatsApp">${whatsappIcon()}</a><dialog id="detail-dialog"><button class="close-dialog icon-button" aria-label="Close dialog">${icon('x')}</button><div id="detail-content"></div></dialog>
 <dialog id="basket-dialog"><button class="close-dialog icon-button" aria-label="Close quote basket">${icon('x')}</button><div class="eyebrow">YOUR EQUIPMENT LIST</div><h2>Quote basket</h2><p>Build your list. Our team will confirm models, availability, and pricing.</p><div id="basket-items"></div><a id="request-quote" class="button primary" target="_blank" rel="noopener">Request quote on WhatsApp ${icon('arrow-up-right')}</a></dialog><div id="toast" role="status"></div>`;
const refreshIcons = () => {
 createIcons({icons});
 document.querySelectorAll('a[href^="https://wa.me/"], #consultation-form button[type="submit"]').forEach(element => {
  if (!element.querySelector('.whatsapp-logo')) element.insertAdjacentHTML('afterbegin', whatsappIcon());
 });
};
let currentFilter='All products',query='';
function renderProducts(){
 const filtered=products.filter(p=>(currentFilter==='All products'||p.category===currentFilter)&&`${p.name} ${p.brand} ${p.desc}`.toLowerCase().includes(query));
 document.querySelector('#products').innerHTML=filtered.length?filtered.map(p=>`<article class="product-card"><button class="product-image" data-product="${p.id}" aria-label="View ${p.name}"><span class="product-badge">${p.badge}</span>${productArt(p.type)}<span class="view-product">View details ${icon('arrow-up-right')}</span></button><div class="product-body"><span class="product-brand">${p.brand}</span><h3><button data-product="${p.id}">${p.name}</button></h3><p>${p.desc}</p><div class="product-bottom"><span>Price on request<small>Tailored to your requirements</small></span><button class="add-product" data-add="${p.id}" aria-label="Add ${p.name} to quote basket">${icon('plus')}</button></div></div></article>`).join(''):`<div class="empty-search">${icon('search')}<h3>No products found</h3><p>Try another search or category.</p><button class="text-link" id="reset-search">Clear filters ${icon('arrow-right')}</button></div>`;
 refreshIcons();
}
function openDialog(id){document.getElementById(id).showModal();document.body.classList.add('dialog-open');refreshIcons()}
function updateBasket(){
 localStorage.setItem('sky-basket',JSON.stringify(basket));let count=basket.reduce((a,b)=>a+b.qty,0);const badge=document.querySelector('.basket-count');badge.textContent=count;badge.hidden=!count;
 document.querySelector('#basket-items').innerHTML=basket.length?basket.map(item=>{const p=products.find(p=>p.id===item.id);return `<div class="basket-item"><div class="basket-art">${productArt(p.type)}</div><div><h3>${p.name}</h3><span>Price on request</span><div class="quantity"><button data-quantity="${p.id}" data-change="-1" aria-label="Decrease ${p.name} quantity">−</button><span>${item.qty}</span><button data-quantity="${p.id}" data-change="1" aria-label="Increase ${p.name} quantity">+</button><button class="remove-item" data-remove="${p.id}" aria-label="Remove ${p.name}">${icon('trash-2')}</button></div></div></div>`}).join(''):`<div class="empty-basket">${icon('shopping-bag')}<h3>A better setup starts here.</h3><p>Add products to request a personalized quote.</p><button class="button primary" id="browse-products">Explore products ${icon('arrow-right')}</button></div>`;
 const request=document.querySelector('#request-quote');request.hidden=!basket.length;request.href=wa+'?text='+encodeURIComponent('Hello SKY TECH, I would like a quote for:\n'+basket.map(i=>`${i.qty} × ${products.find(p=>p.id===i.id).name}`).join('\n')+'\nPlease confirm available models, specifications, and pricing.');refreshIcons();
}
let toastTimeout;
document.addEventListener('click',e=>{
 const add=e.target.closest('[data-add]');if(add){let id=+add.dataset.add;let item=basket.find(i=>i.id===id);if(item)item.qty++;else basket.push({id,qty:1});updateBasket();const toast=document.querySelector('#toast');toast.textContent='Added to your quote basket';toast.classList.add('visible');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>toast.classList.remove('visible'),2600)}
 const filter=e.target.closest('[data-filter]');if(filter){currentFilter=filter.dataset.filter;document.querySelectorAll('.filter').forEach(f=>f.classList.toggle('selected',f===filter));renderProducts()}
 if(e.target.closest('#reset-search')){currentFilter='All products';query='';document.querySelector('#product-search').value='';document.querySelectorAll('.filter').forEach(f=>f.classList.toggle('selected',f.dataset.filter===currentFilter));renderProducts()}
 if(e.target.closest('.basket-trigger')){updateBasket();openDialog('basket-dialog')}
 const quantity=e.target.closest('[data-quantity]');if(quantity){const item=basket.find(i=>i.id===+quantity.dataset.quantity);item.qty+=+quantity.dataset.change;basket=basket.filter(i=>i.qty>0);updateBasket()}
 const remove=e.target.closest('[data-remove]');if(remove){basket=basket.filter(i=>i.id!==+remove.dataset.remove);updateBasket()}
 if(e.target.closest('.close-dialog'))e.target.closest('dialog').close();
 if(e.target.closest('#browse-products')){document.querySelector('#basket-dialog').close();document.querySelector('#shop').scrollIntoView({behavior:'smooth'})}
 const service=e.target.closest('[data-service]');if(service){const s=services.find(s=>s.id===service.dataset.service);document.querySelector('#detail-content').innerHTML=`<div class="eyebrow">SKY TECH SERVICES</div><h2>${s.title}</h2><p>${s.copy}</p><div class="dialog-art">${productArt(s.id)}</div><ul class="detail-features">${s.features.map(f=>`<li>${icon('check')} ${f}</li>`).join('')}</ul><p>Tell us about your property and requirements. Our team will recommend a suitable setup and discuss installation.</p><a class="button primary" href="${wa}?text=${encodeURIComponent('Hello SKY TECH, I would like to discuss '+s.title+' for my space.')}" target="_blank" rel="noopener">Discuss this service ${icon('arrow-up-right')}</a>`;openDialog('detail-dialog')}
 const product=e.target.closest('[data-product]');if(product){const p=products.find(p=>p.id===+product.dataset.product);document.querySelector('#detail-content').innerHTML=`<div class="eyebrow">${p.brand}</div><h2>${p.name}</h2><div class="dialog-art">${productArt(p.type)}</div><p>${p.desc} Our team can help select the right model for your property and arrange configuration and installation.</p><ul class="detail-features">${p.details.map(item => `<li>${icon('check')} ${item}</li>`).join('')}</ul><p class="catalogue-note">Representative category photography; the pictured equipment is not a confirmed model or stock listing. Your quote will specify the exact products.</p><button class="button primary" data-add="${p.id}">Add to quote basket ${icon('plus')}</button>`;openDialog('detail-dialog')}
 if(e.target.closest('[data-book]')){document.querySelector('#detail-content').innerHTML=`<div class="eyebrow">LET’S PLAN YOUR SETUP</div><h2>Tell us about your space.</h2><p>Fill in a few details to prepare your consultation request on WhatsApp.</p><form id="consultation-form"><label>Your name<input name="name" autocomplete="name" required placeholder="Full name" maxlength="100"></label><label>What can we help with?<select name="service"><option>Wi-Fi & networking</option><option>CCTV & security</option><option>Smart home solutions</option><option>Cabling & IT support</option><option>Product advice</option></select></label><label>Your space<select name="property"><option>Home / apartment</option><option>Villa</option><option>Office</option><option>Retail / business</option></select></label><label>Anything we should know?<textarea name="notes" rows="3" placeholder="Location, coverage issues, or equipment you need…" maxlength="1200"></textarea></label><button class="button primary" type="submit">Continue to WhatsApp ${icon('arrow-up-right')}</button><small>You’ll review and send your message in WhatsApp.</small></form>`;openDialog('detail-dialog')}
 if(e.target.closest('.menu-toggle')){let button=document.querySelector('.menu-toggle');let open=button.getAttribute('aria-expanded')!=='true';button.setAttribute('aria-expanded',open);document.querySelector('nav').classList.toggle('is-open',open)}
 if(e.target.closest('nav a')){document.querySelector('nav').classList.remove('is-open');document.querySelector('.menu-toggle').setAttribute('aria-expanded','false')}
});
document.addEventListener('submit',e=>{if(e.target.id==='consultation-form'){e.preventDefault();const data=new FormData(e.target);const msg=`Hello SKY TECH, I'm ${data.get('name')}. I'd like a consultation for ${data.get('service')} at my ${data.get('property')}.\n${data.get('notes')}`;window.open(wa+'?text='+encodeURIComponent(msg),'_blank','noopener')}});
document.querySelector('#product-search').addEventListener('input',e=>{query=e.target.value.toLowerCase().trim();renderProducts()});
document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('close',()=>document.body.classList.remove('dialog-open'));d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});
mountHero();renderProducts();updateBasket();refreshIcons();
setupNavigation(products, services, value => {
 currentFilter='All products';query=value.toLowerCase();
 document.querySelector('#product-search').value=value;
 document.querySelectorAll('.filter').forEach(f=>f.classList.toggle('selected',f.dataset.filter===currentFilter));
 renderProducts();
 document.querySelector('#shop').scrollIntoView({behavior:'smooth'});
});
